// Plain-English explanations for every concept in the app. Used by <InfoTip/>
// (hover popovers next to terms) and the Learn page. Keep it friendly.

export interface Term {
  key: string;
  term: string;
  short: string; // one line, shown in the hover popover
  long: string; // a paragraph, shown on the Learn page
  example?: string;
  category: "Order book" | "Strategy" | "P&L" | "General";
}

export const GLOSSARY: Term[] = [
  { key: "order-book", term: "Order book", category: "Order book",
    short: "The live list of everyone's buy and sell offers.",
    long: "Every market has an order book: buyers post bids (offers to buy) and sellers post asks (offers to sell), each at a price and size. It's like a shop's price list, but two-sided and constantly changing.",
    example: "100 shares wanted at 0.45, 80 offered at 0.47." },
  { key: "bid", term: "Bid", category: "Order book",
    short: "The highest price a buyer will pay right now.",
    long: "The best bid is the top buy offer in the book. If you want to sell instantly, this is the price you'd get.",
    example: "Best bid 0.45 = someone will buy at 45¢." },
  { key: "ask", term: "Ask", category: "Order book",
    short: "The lowest price a seller will accept right now.",
    long: "The best ask is the cheapest sell offer. If you want to buy instantly, this is what you'd pay.",
    example: "Best ask 0.47 = cheapest seller wants 47¢." },
  { key: "spread", term: "Spread", category: "Order book",
    short: "The gap between the best bid and best ask.",
    long: "Spread = ask − bid. It's the market maker's potential profit per share: buy at the bid, sell at the ask, keep the difference. Wider spread = more profit per trade but fewer trades.",
    example: "Ask 0.47 − bid 0.45 = 0.02 spread." },
  { key: "mid", term: "Midpoint", category: "Order book",
    short: "Halfway between bid and ask — a 'fair price' proxy.",
    long: "The midpoint is (bid + ask) / 2. The app uses it as its estimate of the true price, and quotes around it.",
    example: "Bid 0.45, ask 0.47 → mid 0.46." },
  { key: "tick", term: "Tick size", category: "Order book",
    short: "The smallest price step a market allows.",
    long: "Prices snap to a grid. A 0.01 tick means prices move in whole cents; 0.001 allows tenths of a cent. Your spread can't be tighter than one tick per side.",
    example: "Tick 0.01 → 0.45, 0.46, 0.47…" },
  { key: "liquidity", term: "Liquidity", category: "General",
    short: "How much size is resting, ready to trade against.",
    long: "A liquid market has lots of orders close to the price, so you can trade size without moving it much. Thin markets are riskier to quote in.",
    example: "$84k of liquidity near the touch." },
  { key: "volume", term: "Volume", category: "General",
    short: "How much has actually traded (here, last 24h).",
    long: "Volume shows how active a market is. Busier markets give a market maker more chances to earn the spread.",
    example: "$1.2M traded in 24h." },
  { key: "market-maker", term: "Market making", category: "Strategy",
    short: "Quoting a buy AND a sell to earn the spread.",
    long: "Instead of betting on direction, a market maker posts both a bid and an ask and profits from the gap when both get filled. You're the shop, not the shopper.",
    example: "Buy at 0.45, sell at 0.47, keep 0.02." },
  { key: "inventory", term: "Inventory (position)", category: "Strategy",
    short: "The net shares you're holding right now.",
    long: "As your orders fill you accumulate inventory — positive if you're long (own shares), negative if short. A market maker wants this near zero, because holding a big position is directional risk.",
    example: "+100 means you're long 100 shares." },
  { key: "skew", term: "Inventory skew", category: "Strategy",
    short: "Shifting your quotes to lean against your inventory.",
    long: "When you build up inventory, skew nudges both quotes so you're keener to trade it back off — e.g. if you're long, it lowers your prices to sell sooner. Keep skew smaller than half your spread or it dumps inventory at a loss.",
    example: "Long → quote a bit lower to offload." },
  { key: "widen", term: "Spread widening", category: "Strategy",
    short: "Demanding more edge as your inventory grows.",
    long: "An optional risk control: the more inventory you carry, the wider you quote, so you only take on more risk if you're paid more for it.",
    example: "Bigger position → wider spread." },
  { key: "requote", term: "Re-quote threshold", category: "Strategy",
    short: "How far the market must move before you replace orders.",
    long: "Cancelling and re-posting on every tiny wiggle is wasteful. The threshold means you only re-quote when the price has moved enough to matter.",
    example: "Only re-quote if mid moves ≥ 0.002." },
  { key: "fill", term: "Fill", category: "P&L",
    short: "A trade that actually happened against your order.",
    long: "When someone trades with your resting bid or ask, that's a fill. Fills change your inventory and your P&L.",
    example: "Your 0.45 bid filled → you bought." },
  { key: "realized-pnl", term: "Realized P&L", category: "P&L",
    short: "Profit you've locked in by completing round-trips.",
    long: "Realized profit/loss is settled — you bought and then sold (or vice-versa). It won't change once booked.",
    example: "Bought 0.45, sold 0.47 → +0.02 realized." },
  { key: "unrealized-pnl", term: "Unrealized P&L", category: "P&L",
    short: "Paper profit/loss on what you still hold.",
    long: "Unrealized P&L marks your open position at the current mid. It moves up and down until you close the position.",
    example: "Hold at 0.45, mid now 0.46 → +0.01 paper." },
  { key: "win-rate", term: "Win rate", category: "P&L",
    short: "Share of completed round-trips that made money.",
    long: "Of all the times you opened and closed a position, how often did you come out ahead? High win rate with small wins can still lose if the losses are big.",
    example: "7 of 10 round-trips green → 70%." },
  { key: "drawdown", term: "Max drawdown", category: "P&L",
    short: "The worst peak-to-trough drop in your P&L.",
    long: "How far your running profit fell from its highest point. A measure of how scary the ride got, regardless of where you ended.",
    example: "Peaked +5, fell to −3 → drawdown 8." },
  { key: "sharpe", term: "Sharpe ratio", category: "P&L",
    short: "Return relative to how bumpy the ride was.",
    long: "Higher Sharpe means steadier earnings per unit of wobble. Here it's a relative score for comparing settings, not an annualised finance number.",
    example: "Smooth +profit → high Sharpe." },
  { key: "adverse-selection", term: "Adverse selection", category: "Strategy",
    short: "Getting filled right when the price moves against you.",
    long: "A passive quote tends to fill exactly when informed traders push the price through it — so you buy just before it drops, or sell just before it rises. It's the main reason naive market making loses in trending markets.",
    example: "Your bid fills as the market keeps falling." },
  { key: "pusd", term: "pUSD", category: "General",
    short: "Polymarket's collateral token; 1 pUSD ≈ $1.",
    long: "Since the 2026 CLOB V2 upgrade, Polymarket trades are collateralised in pUSD, an ERC-20 backed 1:1 by USDC. Prices are probabilities from 0 to 1; a share pays 1 pUSD if its outcome happens.",
    example: "0.46 = 46% chance, costs 0.46 pUSD." },
  { key: "backtest", term: "Backtest", category: "General",
    short: "Replaying past data to test a strategy.",
    long: "Instead of waiting live, a backtest feeds historical (or recorded) market data through the strategy so you can see how it would have done — instantly and repeatably.",
    example: "Replay yesterday's book in one second." },
  { key: "sweep", term: "Parameter sweep", category: "General",
    short: "Running many settings to compare them.",
    long: "A sweep backtests a whole grid of spread/size/skew values on the same data and ranks them, so you find good settings instead of guessing one at a time.",
    example: "Try 12 combos, keep the best." },
  { key: "simulation", term: "Simulation", category: "General",
    short: "Fake fills against the real book — no real money.",
    long: "Everything in this app is simulated: it watches the real order book but only pretends to trade. The fill model is optimistic, so treat simulated P&L as a comparison tool, not a promise.",
    example: "Quotes are computed, never sent." },
];

export const byKey: Record<string, Term> = Object.fromEntries(GLOSSARY.map((t) => [t.key, t]));
